### ISSUE TITLE
[4.19.1] US Autocomplete Pro `GEOLOCATE_TYPE_NONE` constant should be `"none"`, not `null`

### ISSUE THREAD

**Issue by shengslogar** [smartystreets/smartystreets-php-sdk#48]
The following constant is defined incorrectly, and should be `"none"`:

https://github.com/smartystreets/smartystreets-php-sdk/blob/15aef42018c7ea7b39e89fe821da24a663876a8f/src/US_Autocomplete_Pro/GeolocateType.php#L8-L10

[Per the docs](https://www.smarty.com/docs/cloud/us-autocomplete-pro-api#pro-http-request-input-fields):

> Acceptable values [of `prefer_geolocation`] are: empty string (which defaults to city), none, or city. 

Additionally, these constants collide with identical ones defined in the deprecated [`\SmartyStreets\PhpSdk\US_Autocomplete\GeolocateType`](https://github.com/smartystreets/smartystreets-php-sdk/blob/15aef42018c7ea7b39e89fe821da24a663876a8f/src/US_Autocomplete/GeolocateType.php#L5-L11) class, as [`define`d constants do not automatically inherit their parent namespace](https://www.php.net/manual/en/function.define.php#90282).

It's also worth noting there's no way to pass an `X-Forwarded-For` header containing a user's IP address, diminishing the value of the geolocation component of this SDK altogether, since the chance of a server being located in an end user's vicinity is relatively slim. I would consider such an addition a separate feature request, however.

**EDIT:** "collide" isn't perfectly correct terminology, since `!defined` is being called first, but since both files are autoloaded, there is no way to choose between constants defined in each file if/when they differ, and the value you end up with is at the mercy of Composer's autoloading strategy.

**Comment by smartyeric** [comment]
Hi,

It looks like your issue can be split into three different sections: GEOLOCATE_TYPE_NONE null vs 'none', X-Forwarded-For, and the namespace collision. I'll address these all separately in my response.

GEOLOCATE_TYPE_NONE:
The intent behind setting this constant to null by default is to not send the parameter in the request at all. 'none' is the default value, so functionally, not sending the parameter at all will result in a value of none. The intention behind not sending the parameter (rather than sending the parameter with a value of 'none') is to increase readability of http requests (if they are captured). If you have any further concerns regarding this, please reach out.

X-Forwarded-For:
This was something we overlooked. I have since added this feature in the latest release. You can now pass an X-Forwarded-For header using the withXForwardedFor method of ClientBuilder. Thank you for bringing this to our attention!

Namespace Collision:
As you mentioned, the US_Autocomplete classes are deprecated, given that they point to the old US Autocomplete Basic API, which is no longer functional. We had left these classes in to support those who were still using the US Autocomplete Basic API, but now that the API is completely non-functional, we felt it prudent to remove the US_Autocomplete classes in order to avoid the aforementioned namespace collision with the newer US_Autocomplete_Pro classes.

Thank you for bringing these issues in. If you have any questions regarding our solutions or answers, please reach out.

**Comment by shengslogar** [comment]
Appreciate the detailed reply! 🙏
